### ISSUE TITLE
Add explicit link to the astroNN_apogee_dr14_catalog.fits file in the README

### ISSUE THREAD

**Issue by jobovy** [henrysky/astroNN_spectra_paper_figures#2]
I was just looking for the fits file with the catalog and I don't think it's linked to anywhere in the README, so for clarity I think it would be best to put an explicit link in the README. Maybe both in the ``Getting Started`` section and in the ``astroNN Apogee DR14 Stellar Parameters and Abundances``.

**Comment by henrysky** [comment]
fixed in e3f7889
